# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c010e68ecf4932c4cfaf740bfa4f8445c1f28db3e0faf020eca6d87bd8c36d4a926ac98982a4f43e4e53fb7f83c030e96968e4a4d5b924232bd7b1f0d794f57c

test:
  secret_key_base: fc58694d37bec5405c052d98dd057dce95a8fcea28dc2e8781207376773804faca855222ba1ea95592137850d80247cf36246541f210d6e99df68d622170172b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
